// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5uXP9yxVOLvN60y7d6nQcF4NBCAt6lI',
    appId: '1:606386924997:web:4aee7115faeb44e02dafac',
    messagingSenderId: '606386924997',
    projectId: 'bookme-c907d',
    authDomain: 'bookme-c907d.firebaseapp.com',
    storageBucket: 'bookme-c907d.appspot.com',
    measurementId: 'G-0SDRKW9Y6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21ts86XD5Q6M5cAd4BAee7vOYUJIVeeI',
    appId: '1:606386924997:android:d1497dc016381ead2dafac',
    messagingSenderId: '606386924997',
    projectId: 'bookme-c907d',
    storageBucket: 'bookme-c907d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIIgHep075S6mL4GACeQDTfXCEtoC1oE',
    appId: '1:606386924997:ios:c5049b467802ada02dafac',
    messagingSenderId: '606386924997',
    projectId: 'bookme-c907d',
    storageBucket: 'bookme-c907d.appspot.com',
    iosBundleId: 'com.example.bookme',
  );
}
